application: focused-sprite-91100
version: 1
runtime: go
api_version: go1

handlers:
- url: /playground
  static_files: playground.html
  upload: playground.html

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /compile
  script: _go_app
