application: focused-sprite-91100
version: 1
runtime: go
api_version: go1

handlers:
- url: /playground/blog-post
  static_files: blogpost.html
  upload: blogpost.html

- url: /playground
  static_files: playground.html
  upload: playground.html

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /bower_components
  static_dir: bower_components

- url: /compile
  script: _go_app

- url: /compile-normal
  script: _go_app
